INSERT INTO products (name, size, category, distributor)
VALUES  --Vodka
        ('Fremont Mishcheif' , 'liter' , 'Vodka' , 'NW Beverage'),
        ('Galens' , '750' , 'Vodka' , 'Columbia'),
        ('Stolichanay' , 'liter' , 'Vodka' , 'RNDC'),
        ('Stolichnaya Vanilla' , 'liter' , 'Vodka' , 'RNDC'),
        ('Titos' , 'liter' , 'Vodka' , 'RNDC'),
        ('Absolut' , 'liter' , 'Vodka' , 'SGWS'),
        ('Absolut Citron' , 'liter' , 'Vodka' , 'SGWS'),
        ('Absolut Mandarin' , 'liter' , 'Vodka' , 'SGWS'),
        ('Belvedere' , 'liter' , 'Vodka' , 'SGWS'),
        ('Grey Goose' , 'liter' , 'Vodka' , 'SGWS'),
        ('Haku' , 'liter' , 'Vodka' , 'SGWS'),
        ('Ketel One' , 'liter' , 'Vodka' , 'SGWS'),
        ('Nikka' , 'liter' , 'Vodka' , 'SGWS'),
        ('Reyka' , 'liter' , 'Vodka' , 'SGWS'),
        ('Wheatley' , 'liter' , 'Vodka' , 'SGWS'),
        --Rum
        ('Jolly Roger' , 'liter' , 'Rum' , 'NW Beverage'),
        ('Myers Dark' , 'liter' , 'Rum' , 'RNDC' ),
        ('Zaya 16y' , 'liter' , 'Rum' , 'RNDC' ),
        ('Zaya Alta Fuerza' , 'liter' , 'Rum' , 'RNDC' ),
        ('Captain Morgan' , 'liter' , 'Rum' , 'SGWS' ),
        ('Malibu Coconut' , 'liter' , 'Rum' , 'SGWS' ),
        ('Malibu Passionfruit' , 'liter' , 'Rum' , 'SGWS' ),
        --Gin
        ('Constant Reader' , 'liter' , 'Gin' , 'NW Beverage' ),
        ('The Botanist' , 'liter' , 'Gin' , 'RNDC' ),
        ('Hendricks' , 'liter' , 'Gin' , 'RNDC' ),
        ('Bombay' , 'liter' , 'Gin' , 'SGWS' ),
        ('Bombay Sapphire' , 'liter' , 'Gin' , 'SGWS' ),
        ('Nolets' , 'liter' , 'Gin' , 'SGWS' ),
        ('Roku' , 'liter' , 'Gin' , 'SGWS' ),
        ('Tanqueray' , 'liter' , 'Gin' , 'SGWS' ),
        ('Tanqueray 10' , 'liter' , 'Gin' , 'SGWS' ),
        ('Aviation' , 'liter' , 'Gin' , 'SGWS' ),
        ('Beefeater' , 'liter' , 'Gin' , 'SGWS' ),
        ('Big Gin' , 'liter' , 'Gin' , 'SGWS' ),
        --Tequila/Mezcal
        ('123 Diablito' , 'liter' , 'Tequila/Mezcal' , 'NW Beverage' ),
        ('123 Dos Reposado' , 'liter' , 'Tequila/Mezcal' , 'NW Beverage' ),
        ('Granja Joven' , 'liter' , 'Tequila/Mezcal' , 'NW Beverage' ),
        ('Herradura' , 'liter' , 'Tequila/Mezcal' , 'RNDC' ),
        ('Hussongs' , 'liter' , 'Tequila/Mezcal' , 'RNDC' ),
        ('Pueblo Viejo' , 'liter' , 'Tequila/Mezcal' , 'Columbia' ),
        ('Siete Leguas' , 'liter' , 'Tequila/Mezcal' , 'RNDC' ),
        ('1800 Reposado' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('1800 Silver' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Avion Reposado' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Don Julio 1942' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Don Julio Anejo' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Don Julio Blanco' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Patron Grand Platinum' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Patron Silver' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        ('Teremana' , 'liter' , 'Tequila/Mezcal' , 'SGWS' ),
        --Congac
        ('Remy Martin 1738' , '750' , 'Cognac' , 'RNDC' ),
        ('Remy VSOP' , '750' , 'Cognac' , 'RNDC' ),
        ('Courvosier' , '750' , 'Cognac' , 'SGWS' ),
        ('Hennessey VS' , '750' , 'Cognac' , 'SGWS' ),
        --Cordial/Liquer
        ('Lionello dry Vermouth' , 'liter' , 'Cordial/Liquer' , 'NW Beverage' ),
        ('Lionello sweet vermouth' , 'liter' , 'Cordial/Liquer' , 'NW Beverage' ),
        ('Chambord' , 'liter' , 'Cordial/Liquer' , 'RNDC' ),
        ('Cointreau' , 'liter' , 'Cordial/Liquer' , 'RNDC' ),
        ('Disaronno Amaretto' , 'liter' , 'Cordial/Liquer' , 'RNDC' ),
        ('Giffard Lychee' , 'liter' , 'Cordial/Liquer' , 'RNDC' ),
        ('Aperol' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Baileys' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Campari' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Domane de Canton Ginger' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Frangelico' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('Grand Marnier' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Green Chartreuse' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('Kahlua' , 'liter' , 'Cordial/liquer' , 'SGWS' ),
        ('Luxardo Maraschino' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('Midori' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('St. Germain' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('Triple Sec' , '750' , 'Cordial/liquer' , 'SGWS' ),
        ('Shiso liquer' , '750' , 'Cordial/liquer' , 'I.A.' ),
        ('St.Elizabeth Allspice' , '750' , 'Cordial/liquer' , 'I.A.' ),
        --Sake RNDC/SGWS
        ('Morimoto' , '1.8l' , 'Sake' , 'RNDC' ),
        ('Black Dragon' , '1.8l' , 'Sake' , 'SGWS' ),
        ('Yuki No Bosha' , '1.8l' , 'Sake' , 'RNDC' ),
        ('7 Spearman' , '1.8l' , 'Sake' , 'RNDC' ),
        ('Awa Yuki' , '300ml' , 'Sake' , 'RNDC' ),
        ('Hakutsuru Premium' , '320' , 'Sake' , 'RNDC' ),
        ('Sayuri Nigori' , '320' , 'Sake' , 'RNDC' ),
        ('Momokawa Pearl' , '300' , 'Sake' , 'RNDC' ),
        ('Hakutsuru Plum' , '720' , 'Sake' , 'RNDC' ),
        ('Ippongi Spicy Plum' , '720' , 'Sake' , 'RNDC' ),
        ('Momokawa Diamond' , '720' , 'Sake' , 'RNDC' ),
        ('Momokawa Silver' , '720' , 'Sake' , 'RNDC' ),
        ('Moonstone Pear' , '720' , 'Sake' , 'RNDC' ),
        ('Moonstone Coconut Lemongrass' , '720' , 'Sake' , 'RNDC' ),
        ('Sayuri Lg.' , '720' , 'Sake' , 'RNDC' ),
        ('Cowboy Yamahai' , '720' , 'Sake' , 'RNDC' ),
        ('Takatenjin' , '720' , 'Sake' , 'RNDC' ),
        ('Endless Summer' , '720' , 'Sake' , 'RNDC' ),
        ('Black Dragon S.' , '720' , 'Sake' , 'SGWS' ),
        ('Tyku Coconut' , '720' , 'Sake' , 'SGWS' ),
        ('Tyku Cucumber' , '720' , 'Sake' , 'SGWS' ),
        --Sake COHO IMPORTS
        ('Dassai39' , '720' , 'Sake' , 'COHO Imports' ),
        ('Dassai45' , '720' , 'Sake' , 'COHO Imports' ),
        ('Hakkaisan' , '720' , 'Sake' , 'COHO Imports' ),
        ('Hana Fuji Apple' , '720' , 'Sake' , 'COHO Imports' ),
        ('Hana Lychee' , '720' , 'Sake' , 'COHO Imports' ),
        ('Hana White Peach' , '720' , 'Sake' , 'COHO Imports' ),
        ('Katana' , '720' , 'Sake' , 'COHO Imports' ),
        ('Michinoku Onikiroshi' , '720' , 'Sake' , 'COHO Imports' ),
        ('Bizen Mabaroshi' , '300' , 'Sake' , 'COHO Imports' ),
        ('Sho Chiku Bai Nama Organic' , '300' , 'Sake' , 'COHO Imports' ),
        ('Taisetsu Ice Dome' , '300' , 'Sake' , 'COHO Imports' ),
        ('Yuki Strawberry Nigori' , '300' , 'Sake' , 'COHO Imports' ),
        ('Hot Sake Cube' , '15l' , 'Sake' , 'COHO Imports' ),
        ('Jinro Soju' , '2l' , 'Sake' , 'COHO Imports' ),
        --Whiskey, Canadian
        ('Crown Royal' , 'liter' , 'Whiskey/Canadian' , 'SGWS' ),
        ('Crown Royal Peach' , 'liter' , 'Whiskey/Canadian' , 'SGWS' ),
        ('Crown XO' , 'liter' , 'Whiskey/Canadian' , 'SGWS' ),
        --Whiskey, Scotch
        ('Balvenie 12' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Balvenie 15' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Glenfiddich 12' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Glenfiddich 15' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Macallan 12' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Macallan 18' , '750' , 'Whiskey/Scotch' , 'RNDC' ),
        ('Glenlivet 12' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Glenlivet 15' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Johnny Walker Black' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Johnny Walker Blue' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Oban 14' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Oban Distillers Choice' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Ardbeg Wee Beastie' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Glenmorangie 10' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Glenmorangie 14' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        ('Glenmorangie Nectar d or' , '750' , 'Whiskey,Scotch' , 'SGWS' ),
        --Whiskey,Irish
        ('Jameson' , '750' , 'Whiskey,Irish' , 'SGWS' ),
        ('Proper No 12' , '750' , 'Whiskey,Irish' , 'SGWS' ),
        --Whiskey, Japanese
        ('Hakushu 12' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Hibiki' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Hibiki 21' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Coffey Grain' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Coffe Malt' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Miyagikyo' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Taketsuru' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Whiskey F/The Barrel' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Nikka Yoichi' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Suntory AO' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Suntory Toki' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Yamazaki 12' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Yamazaki 18' , '750' , 'Whiskey,Japanese' , 'SGWS' ),
        ('Kamiki' , '750' , 'Whiskey, Japanese' , 'RNDC' ),
        ('Kamiki Intense' , '750' , 'Whiskey, Japanese' , 'RNDC' ),
        ('The Chita' , '750' , 'Whiskey, Japanese' , 'I.A.' ),
        --Whiskey,Bourbon
        ('Fremont Mischief' , 'liter' , 'Whiskey,Bourbon' , 'NW Beverage' ),
        ('Buffalo Trace' , '750' , 'Whiskey,Bourbon' , 'Columbia' ),
        ('Eagle Rare 10' , '750' , 'Whiskey,Bourbon' , 'Columbia' ),
        ('Old Forester' , '750' , 'Whiskey,Bourbon' , 'RNDC' ),
        ('Woodford Reserve' , '750' , 'Whiskey,Bourbon' , 'RNDC' ),
        ('Bulleit Bourbon' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        ('Knob Creek' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        ('Makers Mark' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        ('Legent' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        ('Woodinville Bourbon' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        ('Woodinville Port Cask' , '750' , 'Whiskey,Bourbon' , 'SGWS' ),
        --Whiskey/Rye
        ('James Oliver' , '750' , 'Whiskey,Rye' , 'NW Beverage' ),
        ('Sazerac' , '750' , 'Whiskey,Rye' , 'Columbia' ),
        ('Jack Daniels' , '750' , 'Whiskey,Rye' , 'RNDC' ),
        ('Screwball' , '750' , 'Whiskey,Rye' , 'RNDC' ),
        ('Whistlepig 10' , '750' , 'Whiskey,Rye' , 'RNDC' ),
        ('Bulleit Rye' , '750' , 'Whiskey,Rye' , 'SGWS' ),
        ('Pendleton' , '750' , 'Whiskey,Rye' , 'SGWS' ),
        ('Woodinville Rye' , '750' , 'Whiskey,Rye' , 'SGWS' ),
        --WINE
        ('Carmel Road Pinot Noir' , '750' , 'Wine' , 'SGWS' ),
        ('Chandon Spritz' , '750' , 'Wine' , 'SGWS' ),
        ('Chateau St. Michelle' , '750' , 'Wine' , 'SGWS' ),
        ('Fortress Cab' , '750' , 'Wine' , 'SGWS' ),
        ('Mantanzas Creek Merlot' , '750' , 'Wine' , 'SGWS' ),
        ('Moet Imperial' , '750' , 'Wine' , 'SGWS' ),
        ('Siduri Chard' , '750' , 'Wine' , 'SGWS' ),
        ('Terrazas Malbec' , '750' , 'Wine' , 'SGWS' ),
        ('Conundrum' , '750' , 'Wine' , 'RNDC' ),
        ('J Lohr Reisling' , '750' , 'Wine' , 'RNDC' ),
        ('Bonoval Sparkling Rose' , '750' , 'Wine' , 'NW Beverage' ),
        ('Deer and Finch Chard' , '750' , 'Wine' , 'NW Beverage' ),
        ('La Bella Prosecco' , '750' , 'Wine' , 'NW Beverage' ),
        ('Lange Pinot Noir' , '750' , 'Wine' , 'NW Beverage' ),
        ('Ruby Sky Cab' , '750' , 'Wine' , 'NW Beverage' ),
        ('Ryan Patrick Red' , '750' , 'Wine' , 'NW Beverage' ),
        ('Vandori Pinot Grigio' , '750' , 'Wine' , 'NW Beverage' );

--('' , '' , '' , '' ),

