INSERT INTO products (name, size, category, RetailPrice, distributor)
VALUES  --Vodka
        ('Fremont Mishcheif' , 'liter' , 'Vodka' , 3, 'NW Beverage'),
        ('Galens' , '750' , 'Vodka' , null, 'Columbia'),
        ('Stolichnaya' , 'liter' , 'Vodka' , 9, 'RNDC'),
        ('Stolichnaya Vanilla' , 'liter' , 'Vodka' , 9, 'RNDC'),
        ('Titos' , 'liter' , 'Vodka' , 10, 'RNDC'),
        ('Absolut' , 'liter' , 'Vodka' , 9, 'SGWS'),
        ('Absolut Citron' , 'liter' , 'Vodka' , 9, 'SGWS'),
        ('Absolut Mandarin' , 'liter' , 'Vodka' , 9, 'SGWS'),
        ('Belvedere' , 'liter' , 'Vodka' , 10, 'SGWS'),
        ('Grey Goose' , 'liter' , 'Vodka' , 11, 'SGWS'),
        ('Haku' , 'liter' , 'Vodka' , 11, 'SGWS'),
        ('Ketel One' , 'liter' , 'Vodka' , 10, 'SGWS'),
        ('Nikka' , 'liter' , 'Vodka' , 9, 'SGWS'),
        ('Reyka' , 'liter' , 'Vodka' , 11, 'SGWS'),
        ('Wheatley' , 'liter' , 'Vodka' , 9, 'SGWS'),
        --Rum
        ('Bacoo 5 Year','750', 'Rum',11, 'NW Beverage'),
        ('Bacoo 8 Year','750', 'Rum', 12, 'NW Beverage'),
        ('Bacoo 12 Year','750', 'Rum',13, 'NW Beverage'),
        ('Jolly Roger' , 'liter' , 'Rum' , 9, 'NW Beverage'),
        ('Myers Dark' , 'liter' , 'Rum' , 9, 'RNDC' ),
        ('Zaya 16y' , 'liter' , 'Rum' , 11, 'RNDC' ),
        ('Zaya Alta Fuerza' , 'liter' , 'Rum' , 13, 'RNDC' ),
        ('Captain Morgan' , 'liter' , 'Rum' , 9, 'SGWS' ),
        ('Malibu Coconut' , 'liter' , 'Rum' , 9, 'SGWS' ),
        ('Malibu Passionfruit' , 'liter' , 'Rum' , 8, 'SGWS' ),
        --Gin
        ('Constant Reader' , 'liter' , 'Gin' , 8, 'NW Beverage' ),
        ('The Botanist' , 'liter' , 'Gin' , 13, 'RNDC' ),
        ('Hendricks' , 'liter' , 'Gin' ,  10, 'RNDC' ),
        ('Bombay' , 'liter' , 'Gin' , 9, 'SGWS' ),
        ('Bombay Sapphire' , 'liter' , 'Gin' , 10, 'SGWS' ),
        ('Nolets' , 'liter' , 'Gin' , 11, 'SGWS' ),
        ('Roku' , 'liter' , 'Gin' , 3.75,'SGWS' ),
        ('Tanqueray' , 'liter' , 'Gin' , 9, 'SGWS' ),
        ('Tanqueray 10' , 'liter' , 'Gin' , 11, 'SGWS' ),
        ('Tanqueray Sevilla', '750', 'Gin', 12, 'SGWS'),
        ('Aviation' , 'liter' , 'Gin' , 10, 'SGWS' ),
        ('Beefeater' , 'liter' , 'Gin' , 8, 'SGWS' ),
        ('Big Gin' , 'liter' , 'Gin' , 8.25, 'SGWS' ),
        ('Woodcut Barrel Gin', '750', 'Gin',12, 'NW Beverage'),
        --Tequila/Mezcal
        ('123 Diablito' , 'liter' , 'Tequila/Mezcal' , 50, 'NW Beverage' ),
        ('123 Dos Reposado' , 'liter' , 'Tequila/Mezcal' , 13, 'NW Beverage' ),
        ('Granja Joven' , 'liter' , 'Tequila/Mezcal' ,14, 'NW Beverage' ),
        ('Herradura' , 'liter' , 'Tequila/Mezcal' , 10, 'RNDC' ),
        ('Hussongs' , 'liter' , 'Tequila/Mezcal' , 10, 'RNDC' ),
        ('Pueblo Viejo' , 'liter' , 'Tequila/Mezcal' , 8, 'Columbia' ),
        ('Siete Leguas' , 'liter' , 'Tequila/Mezcal' , 12, 'RNDC' ),
        ('1800 Reposado' , 'liter' , 'Tequila/Mezcal' , 8, 'SGWS' ),
        ('1800 Silver' , 'liter' , 'Tequila/Mezcal' , 8, 'SGWS' ),
        ('Avion Reposado' , 'liter' , 'Tequila/Mezcal' , 8, 'SGWS' ),
        ('Don Julio 1942' , 'liter' , 'Tequila/Mezcal' , 32, 'SGWS' ),
        ('Don Julio Anejo' , 'liter' , 'Tequila/Mezcal' , 13, 'SGWS' ),
        ('Don Julio Blanco' , 'liter' , 'Tequila/Mezcal' , 12, 'SGWS' ),
        ('Patron Grand Platinum' , 'liter' , 'Tequila/Mezcal' , null, 'Columbia'),
        ('Patron Silver' , 'liter' , 'Tequila/Mezcal' , 12, 'SGWS' ),
        ('Teremana' , 'liter' , 'Tequila/Mezcal' , 9, 'SGWS' ),
        --Congac
        ('Remy Martin 1738' , '750' , 'Cognac' , 12, 'RNDC' ),
        ('Remy VSOP' , '750' , 'Cognac' , 12, 'RNDC' ),
        ('Courvosier' , '750' , 'Cognac' , 10, 'SGWS' ),
        ('Hennessey VS' , '750' , 'Cognac' , 12, 'SGWS' ),
        --Cordial/Liquer
        ('Lionello dry Vermouth' , 'liter' , 'Cordial/Liquer' , 7, 'NW Beverage' ),
        ('Lionello sweet vermouth' , 'liter' , 'Cordial/Liquer' , 7, 'NW Beverage' ),
        ('Chambord' , 'liter' , 'Cordial/Liquer' , 39, 'RNDC' ),
        ('Cointreau' , 'liter' , 'Cordial/Liquer' , 8.50, 'RNDC' ),
        ('Disaronno Amaretto' , 'liter' , 'Cordial/Liquer' , 8, 'RNDC' ),
        ('Giffard Lychee' , 'liter' , 'Cordial/Liquer' , null, 'RNDC' ),
        ('Aperol' , 'liter' , 'Cordial/liquer' , null, 'SGWS' ),
        ('Baileys' , 'liter' , 'Cordial/liquer' , 8, 'SGWS' ),
        ('Campari' , 'liter' , 'Cordial/liquer' , 8, 'SGWS' ),
        ('Domane de Canton Ginger' , 'liter' , 'Cordial/liquer' , 9, 'SGWS' ),
        ('Frangelico' , '750' , 'Cordial/liquer' ,7., 'SGWS' ),
        ('Grand Marnier' , 'liter' , 'Cordial/liquer' ,9.50, 'SGWS' ),
        ('Green Chartreuse' , '750' , 'Cordial/liquer' ,14, 'SGWS' ),
        ('Kahlua' , 'liter' , 'Cordial/liquer' ,6, 'SGWS' ),
        ('Luxardo Maraschino' , '750' , 'Cordial/liquer' , null, 'SGWS' ),
        ('Midori' , '750' , 'Cordial/liquer' , 8, 'SGWS' ),
        ('St. Germain' , '750' , 'Cordial/liquer' , 9.50, 'SGWS' ),
        ('Triple Sec' , '750' , 'Cordial/liquer' , null, 'SGWS' ),
        ('Shiso liquer' , '750' , 'Cordial/liquer' , null, 'I.A.' ),
        ('St.Elizabeth Allspice' , '750' , 'Cordial/liquer' , null, 'I.A.' ),
        
        --Whiskey, Canadian
        ('Crown Royal' , 'liter' , 'Whiskey/Canadian' , 10, 'SGWS' ),
        ('Crown Royal Peach' , 'liter' , 'Whiskey/Canadian' , 10, 'SGWS' ),
        ('Crown XO' , 'liter' , 'Whiskey/Canadian' , 14,'SGWS' ),
        --Whiskey, Scotch
        ('Balvenie 12' , '750' , 'Whiskey/Scotch' , 14, 'RNDC' ),
        ('Balvenie 15' , '750' , 'Whiskey/Scotch' ,22, 'RNDC' ),
        ('Glenfiddich 12' , '750' , 'Whiskey/Scotch' , 12, 'RNDC' ),
        ('Glenfiddich 15' , '750' , 'Whiskey/Scotch' , 15, 'RNDC' ),
        ('Macallan 12' , '750' , 'Whiskey/Scotch' , 14., 'RNDC' ),
        ('Macallan 18' , '750' , 'Whiskey/Scotch' , 36, 'RNDC' ),
        ('Glenlivet 12' , '750' , 'Whiskey,Scotch' , 11, 'SGWS' ),
        ('Glenlivet 15' , '750' , 'Whiskey,Scotch' ,null, 'SGWS' ),
        ('Johnny Walker Black' , '750' , 'Whiskey,Scotch' , 12, 'SGWS' ),
        ('Johnny Walker Blue' , '750' , 'Whiskey,Scotch' ,44, 'SGWS' ),
        ('Oban 14' , '750' , 'Whiskey,Scotch' ,15, 'SGWS' ),
        ('Oban Distillers Choice' , '750', 'Whiskey,Scotch', 44, 'SGWS' ),
        ('Ardbeg Wee Beastie' , '750' , 'Whiskey,Scotch' , 9, 'SGWS' ),
        ('Glenmorangie 10' , '750' , 'Whiskey,Scotch' , 10, 'SGWS' ),
        ('Glenmorangie 14' , '750' , 'Whiskey,Scotch' , 11, 'SGWS' ),
        ('Glenmorangie Nectar d or' , '750' , 'Whiskey,Scotch', 12, 'SGWS' ),
        --Whiskey,Irish
        ('Jameson' , '750' , 'Whiskey,Irish' , 9, 'SGWS' ),
        ('Proper No 12' , '750' , 'Whiskey,Irish' , 9, 'SGWS' ),
        --Whiskey, Japanese
        ('Hakushu 12' , '750' , 'Whiskey,Japanese' , 20, 'SGWS' ),
        ('Hibiki' , '750' , 'Whiskey,Japanese' , 16,  'SGWS' ),
        ('Hibiki 21' , '750' , 'Whiskey,Japanese5' ,105, 'SGWS' ),
        ('Nikka Coffey Grain' , '750' , 'Whiskey,Japanese' ,19, 'SGWS' ),
        ('Nikka Coffe Malt' , '750' , 'Whiskey,Japanese' , 22, 'SGWS' ),
        ('Nikka Miyagikyo' , '750' , 'Whiskey,Japanese' , 22,  'SGWS' ),
        ('Nikka Taketsuru' , '750' , 'Whiskey,Japanese' , 22, 'SGWS' ),
        ('Nikka Whiskey F/The Barrel' , '750' , 'Whiskey,Japanese' ,17, 'SGWS' ),
        ('Nikka Yoichi' , '750' , 'Whiskey,Japanese' , 22, 'SGWS' ),
        ('Suntory AO' , '750' , 'Whiskey,Japanese' , 14, 'SGWS' ),
        ('Suntory Toki' , '750' , 'Whiskey,Japanese' , 11, 'SGWS' ),
        ('Yamazaki 12' , '750' , 'Whiskey,Japanese' , 24, 'SGWS' ),
        ('Yamazaki 18' , '750' , 'Whiskey,Japanese' , 105, 'SGWS' ),
        ('Kamiki' , '750' , 'Whiskey, Japanese' , 12, 'RNDC' ),
        ('Kamiki Intense' , '750' , 'Whiskey, Japanese' ,16, 'RNDC' ),
        ('The Chita' , '750' , 'Whiskey, Japanese' , 24, 'I.A.' ),
        --Whiskey,Bourbon
        ('Fremont Mischief' , 'liter' , 'Whiskey,Bourbon' , 8, 'NW Beverage' ),
        ('Buffalo Trace' , '750' , 'Whiskey,Bourbon' , 9, 'Columbia' ),
        ('Eagle Rare 10' , '750' , 'Whiskey,Bourbon' , 11, 'Columbia' ),
        ('Old Forester' , '750' , 'Whiskey,Bourbon' , 8, 'RNDC' ),
        ('Woodford Reserve' , '750' , 'Whiskey,Bourbon' , 12, 'RNDC' ),
        ('Bulleit Bourbon' , '750' , 'Whiskey,Bourbon' , 9.50, 'SGWS' ),
        ('Knob Creek' , '750' , 'Whiskey,Bourbon' , 9, 'SGWS' ),
        ('Makers Mark' , '750' , 'Whiskey,Bourbon' , 10, 'SGWS' ),
        ('Legent' , '750' , 'Whiskey,Bourbon' , 3.75, 'SGWS' ),
        ('Woodinville Bourbon' , '750' , 'Whiskey,Bourbon' , 12, 'SGWS' ),
        ('Woodinville Port Cask' , '750' , 'Whiskey,Bourbon' , 14, 'SGWS' ),
        --Whiskey/Rye
        ('James Oliver' , '750' , 'Whiskey,Rye' , 12, 'NW Beverage' ),
        ('Sazerac' , '750' , 'Whiskey,Rye' , 9, 'Columbia' ),
        ('Jack Daniels' , '750' , 'Whiskey,Rye' , 9, 'RNDC' ),
        ('Screwball' , '750' , 'Whiskey,Rye' , 7,'RNDC' ),
        ('Whistlepig 10' , '750' , 'Whiskey,Rye' , 12, 'RNDC' ),
        ('Whistlepig 15' , '750' , 'Whiskey,Rye' , 55, 'RNDC' ),
        ('Bulleit Rye' , '750' , 'Whiskey,Rye' , 8.50, 'SGWS' ),
        ('Pendleton' , '750' , 'Whiskey,Rye' , 9, 'SGWS' ),
        ('Woodinville Rye' , '750' , 'Whiskey,Rye' , 13, 'SGWS' ),
        --WINE
        ('Carmel Road Pinot Noir' , '750' , 'Wine', 9, 'SGWS' ),
        ('Chandon Spritz' , '750' , 'Wine' , 10, 'SGWS' ),
        ('Chateau St. Michelle' , '750' , 'Wine' , 11, 'SGWS' ),
        ('Fortress Cab' , '750' , 'Wine' , 13, 'SGWS' ),
        ('Mantanzas Creek Merlot' , '750' ,'Wine' , 15, 'SGWS' ),
        ('Moet Imperial' , '750' , 'Wine' , null, 'SGWS' ),
        ('Siduri Chard' , '750' , 'Wine' , 15, 'SGWS' ),
        ('Terrazas Malbec' , '750' , 'Wine' , 9, 'SGWS' ),
        ('Conundrum' , '750' , 'Wine' , 10, 'RNDC' ),
        ('J Lohr Reisling' , '750' , 'Wine' , 9, 'RNDC' ),
        ('Bonoval Sparkling Rose' , '750' , 'Wine' , 9, 'NW Beverage' ),
        ('Deer and Finch Chard' , '750' , 'Wine' , 12, 'NW Beverage' ),
        ('La Bella Prosecco' , '750' , 'Wine' , 9, 'NW Beverage' ),
        ('Lange Pinot Noir' , '750' , 'Wine' , 14, 'NW Beverage' ),
        ('Ruby Sky Cab' , '750' , 'Wine' , 10, 'NW Beverage' ),
        ('Ryan Patrick Reisling', '750', 'Wine', 9, 'NW Beverage'),
        ('Ryan Patrick Red' , '750' , 'Wine' , 11, 'NW Beverage' ),
        ('Vandori Pinot Grigio' , '750' , 'Wine' , 10, 'NW Beverage' );

--('' , '' , '' , '' ),

